spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: -dev12345678910111213
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-junbaobao-test
