spring:
  profiles:
    active:
      - dev

#开发环境
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    #配置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #配置驱动
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    dbcp2:
      min-idle: 5
      max-total: 5
      initial-size: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #映射文件路径
  type-aliases-package: pojo
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    dbcp2:
      min-idle: 5
      max-total: 5
      initial-size: 5
      max-wait-millis: 200
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: pojo
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml